adx_entityname: adx_webpage
adx_isdefault: false
adx_name: Producto Base
adx_pagetemplateid: 0fd578c1-77d8-4039-b7d1-c0ea092eecb6
adx_type: 756150001
adx_usewebsiteheaderandfooter: true
adx_webtemplateid: a628d9f1-5e1b-49d9-afa5-8c421576e175
