adx_displayorder: 16
adx_enablerating: false
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: true
adx_isroot: false
adx_name: Producto Base
adx_pagetemplateid: 0fd578c1-77d8-4039-b7d1-c0ea092eecb6
adx_parentpageid: dd85f595-7053-4ea7-ae8b-6c6e83b3c442
adx_partialurl: producto-base
adx_publishingstateid: 2d61ec4e-9195-4572-b365-e60cc89687a8
adx_rootwebpageid: 641156af-d697-44b0-a7bc-1b112c3600b0
adx_sharedpageconfiguration: false
adx_title: Producto Base
adx_webpageid: 5419065e-643e-4d9e-ad63-62eb1e8529f7
adx_webpagelanguageid: a0d0cb6a-df93-4eb4-a2e6-ff92d325105e
